package com.fengyang.tallynote.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fengyang.tallynote.greendao.User;
import com.fengyang.tallynote.greendao.Admin;

import com.fengyang.tallynote.greendao.UserDao;
import com.fengyang.tallynote.greendao.AdminDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig adminDaoConfig;

    private final UserDao userDao;
    private final AdminDao adminDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        adminDaoConfig = daoConfigMap.get(AdminDao.class).clone();
        adminDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        adminDao = new AdminDao(adminDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Admin.class, adminDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        adminDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public AdminDao getAdminDao() {
        return adminDao;
    }

}
