package com.whh.tallynote.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.whh.tallynote.greendao.Admin;
import com.whh.tallynote.greendao.User;

import com.whh.tallynote.greendao.AdminDao;
import com.whh.tallynote.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig adminDaoConfig;
    private final DaoConfig userDaoConfig;

    private final AdminDao adminDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        adminDaoConfig = daoConfigMap.get(AdminDao.class).clone();
        adminDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        adminDao = new AdminDao(adminDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Admin.class, adminDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        adminDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public AdminDao getAdminDao() {
        return adminDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
